apiVersion: apps/v1
kind: Deployment
metadata:
  name: applcm
  namespace: default
  labels:
    app: applcm
spec:
  selector:
    matchLabels:
      app: applcm
  replicas: 1
  template:
    metadata:
      labels:
        app: applcm
    spec:
      containers:
        - image: {{ .Values.images.applcm.repository }}:{{ .Values.images.applcm.tag }}
          imagePullPolicy: {{ .Values.images.applcm.pullPolicy }}
          name: applcm
          env:
            - name: LOG_DIR
              value: /var/log/applcm
            - name: LISTEN_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SSL_ENABLED
              value: {{ quote .Values.ssl.enabled }}
            {{- if .Values.ssl.enabled }}
            - name: SSL_KEY_STORE_PATH
              value: /opt/mec/applcm/ssl/keystore.p12
            - name: SSL_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ssl.secretName }}
                  key: keystorePassword
            - name: SSL_KEY_STORE_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ssl.secretName }}
                  key: keystoreType
            - name: SSL_KEY_ALIAS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ssl.secretName }}
                  key: keyAlias
            {{- end }}
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.publicKeySecretName }}
                  key: publicKey
            - name: DEPLOY_TYPE
              value: helm
            - name: MEP_PORT
              value: "30088"
            - name: PROMETHEUS_PORT
              value: "30000"
            - name: PACKAGE_BASE_PATH
              value: /usr/app/packages
            - name: HELM_PLUGIN_PORT
              value: "8081"
            - name: HELM_PLUGIN_ADDRESS
              value: helm-plugin
            - name: TRUSTSTORE_FILE_PATH
              value: /usr/app/edgegallery.client.jks
            - name: TRUSTSTORE_PASSWORD
              value: adminadmin
          ports:
            - containerPort: 8282
          resources: {}
          volumeMounts:
            {{- if .Values.ssl.enabled }}
            - mountPath: /opt/mec/applcm/ssl
              name: applcm-keystore
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: applcm-log
              mountPath: /var/log/applcm
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: ca-certificates
              mountPath: /usr/app/ca-certificates
            {{- end }}
      volumes:
        {{- if .Values.ssl.enabled }}
        - name: applcm-keystore
          secret:
            secretName: {{ .Values.ssl.secretName }}
            items:
              - key: keystore.p12
                path: keystore.p12
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: applcm-log
          hostPath:
            path: /var/log/edgegallery/applcm
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: ca-certificates
          hostPath:
            path: /tmp/applcm/ca-certificates
        {{- end }}
