global:
  ingress:
    enabled: false
  ssl:
    enabled: false
    secretName:
  persistence:
    enabled: false
    storageClassName: nfs-client
  oauth2:
    authServerAddress:
    clients:
      mecm:
        clientId: mecm-fe
        clientSecret: te9Fmv%qaq
images:
  mecmFe:
    repository: edgegallery/mecm-fe
    tag: latest
    pullPolicy: Always
  apiHandlerInfra:
    repository: edgegallery/api-handler-infra
    tag: latest
    pullPolicy: Always
  meoBpmnInfra:
    repository: edgegallery/bpmn-infra
    tag: latest
    pullPolicy: Always
  meoCatalogDbAdapter:
    repository: edgegallery/catalog-db-adapter
    tag: latest
    pullPolicy: Always
  mecmEsr:
    repository: edgegallery/mecm-esr
    tag: latest
    pullPolicy: Always
  meoRequestDbAdapter:
    repository: edgegallery/request-db-adapter
    tag: latest
    pullPolicy: Always
  mecmCatalog:
    repository: edgegallery/mecm-catalog
    tag: latest
    pullPolicy: Always
  mariadb:
    repository: mariadb
    tag: 10.1
    pullPolicy: Always
expose:
  mecmFe:
    port: 8443
    nodePort: 30093