## Global configuration
global:
  servicecenter:
    enabled: true
  usermgmt:
    enabled: true
  appstore:
    enabled: true
  developer:
    enabled: true
  mecm:
    enabled: true
  persistence:
    enabled: false
    storageClassName: nfs-client
  ingress:
    enabled: false
    tls:
      enabled: false
      secretName:
    annotations:
      bodySize: 20m
    hosts:
      auth:
      developer:
      appstore:
      mecm:
  ssl:
    enabled: false
    secretName:
  oauth2:
    authServerAddress:
    clients:
      appstore:
        clientId: appstore-fe
        clientSecret: te9Fmv%qaq
        clientUrl:
      developer:
        clientId: developer-fe
        clientSecret: te9Fmv%qaq
        clientUrl:
      mecm:
        clientId: mecm-fe
        clientSecret: te9Fmv%qaq
        clientUrl:

# Sub charts
## Configuration values for the user-mgmt dependency
##
usermgmt:
  jwt:
    secretName:
#  expose:
#    port: 8067
#    nodePort: 30067
#  images:
#    usermgmt:
#      repository: edgegallery/user-mgmt
#      tag: stable
#      pullPolicy: Always
#    postgres:
#      repository: postgres
#      tag: 9.6.15
#      pullPolicy: IfNotPresent
#    redis:
#      repository: redis
#      tag: 6.0.3
#      pullPolicy: IfNotPresent
#  postgres:
#    username: usermgmt
#    password: te9Fmv%qaq
#    dbname: usermgmtdb
#  cors:
#    allowOrigins: "*"
#  redis:
#    password: te9Fmv%qaq
#    timeout: 1800
#    verificationTimeout: 60
#    maxTotal: 1000
#    maxIdle: 50
#    maxWaitMillis: 100000
#  sms:
#    enabled: false
#    url:
#    appKey:
#    appSecret:
#    sender:
#    templateId:
#    signature:
#    statusCallBack:

# Sub charts
## Configuration values for the appstore dependency
##
#appstore:
#  images:
#    appstoreFe:
#      repository: edgegallery/appstore-fe
#      tag: stable
#      pullPolicy: Always
#    appstoreBe:
#      repository: edgegallery/appstore-be
#      tag: stable
#      pullPolicy: Always
#    postgres:
#      repository: postgres
#      tag: 9.6.15
#      pullPolicy: IfNotPresent
#  postgres:
#    username: appstore
#    password: te9Fmv%qaq
#    dbname: appstoredb
#  expose:
#    appstoreFe:
#      port: 8443
#      nodePort: 30091
#    appstoreBe:
#      port: 8099
#      nodePort: 30099
#    postgres:
#      port: 5432

# Sub charts
## Configuration values for the developer dependency
##
#developer:
#  images:
#    developerFe:
#      repository: edgegallery/developer-fe
#      tag: stable
#      pullPolicy: Always
#    developerBe:
#      repository: edgegallery/developer-be
#      tag: stable
#      pullPolicy: Always
#    postgres:
#      repository: postgres
#      tag: 9.6.15
#      pullPolicy: IfNotPresent
#    toolChain:
#      repository: edgegallery/tool-chain
#      tag: stable
#      pullPolicy: Always
#    portingAdvisor:
#      repository: edgegallery/porting-advisor
#      tag: stable
#      pullPolicy: Always
#  postgres:
#    username: developer
#    password: te9Fmv%qaq
#    dbname: developerdb
#  expose:
#    developerFe:
#      port: 8443
#      nodePort: 30092
#    postgres:
#      port: 5432

# Sub charts
## Configuration values for the mecm dependency
##
#mecm:
#  images:
#    mecmFe:
#      repository: edgegallery/mecm-fe
#      tag: stable
#      pullPolicy: Always
#    apiHandlerInfra:
#      repository: edgegallery/api-handler-infra
#      tag: stable
#      pullPolicy: Always
#    meoBpmnInfra:
#      repository: edgegallery/bpmn-infra
#      tag: stable
#      pullPolicy: Always
#    meoCatalogDbAdapter:
#      repository: edgegallery/catalog-db-adapter
#      tag: stable
#      pullPolicy: Always
#    mecmEsr:
#      repository: edgegallery/mecm-esr
#      tag: stable
#      pullPolicy: Always
#    meoRequestDbAdapter:
#      repository: edgegallery/request-db-adapter
#      tag: stable
#      pullPolicy: Always
#    mecmCatalog:
#      repository: edgegallery/mecm-catalog
#      tag: stable
#      pullPolicy: Always
#    mariadb:
#      repository: mariadb
#      tag: 10.1
#      pullPolicy: Always
#  expose:
#    mecmFe:
#      port: 8443
#      nodePort: 30093

# Sub charts
## Configuration values for the service-center dependency
##
#servicecenter:
#  images:
#    repository: edgegallery/service-center
#    tag: stable
#    pullPolicy: Always